[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[project]
name = "LyCIL"
version = "0.1.2"
description = "A clean, PyTorch Lightning (2.x) continual/incremental learning (CIL) library inspired by PyCIL, with up-to-date methods, NPU support, modern interface, and ready-to-run CLI examples."
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "datasets[vision]>=4.0,<5",
    "jsonargparse[signatures,jsonschema,jsonnet]",
    "scikit-learn>=1.3.2,<1.9.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0",
    "pytest-xdist",
    "pytest-cov",
]

# conflict lightning and lightning-npu
[project.optional-dependencies]
cuda = [
    "torch>=2.7.1,<2.10.0",
    "torchvision",
    "lightning>=2.2.0,<2.6.0",
    "lycil[lightning,wandb]",
]
npu = [
    "torch-npu>=2.1.0",
    "decorator",
    "psutil",
    "importlib_metadata",
    # "lightning @ git+https://github.com/SmallPigPeppa/pytorch-lightning.git@npu_support_fp16_mixed",
    "lycil[wandb]"
]
ghactions = [
    "torch @ https://download.pytorch.org/whl/cpu/torch-2.7.1%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl ; platform_system == 'Linux' and python_version == '3.12' and platform_machine == 'x86_64'",
    "torchvision @ https://download.pytorch.org/whl/cpu/torchvision-0.22.1%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl ; platform_system == 'Linux' and python_version == '3.12' and platform_machine == 'x86_64'",
    "lycil[lightning,wandb]",
]
lightning = [
    "lightning>=2.2.0,<2.6.0",
]
wandb = [
    "wandb>=0.25,<0.30",
]

[project.urls]
source = "https://github.com/Moenupa/LyCIL"
issues = "https://github.com/Moenupa/LyCIL/issues"
releasenotes = "https://github.com/Moenupa/LyCIL/releases"

[tool.uv]
conflicts = [
    [
        { extra = "ghactions" },
        { extra = "cuda" },
        { extra = "npu" },
    ],
]

# if you are using CUDA and wants to specify cuda version
# [tool.uv.sources]
# torch = [
# 	{ index = "pytorch-cu129", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
# ]
# torchvision = [
# 	{ index = "pytorch-cu129", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
# ]
[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.ruff.lint]
ignore = [
    "BLE001",  # blind exception
    "DTZ005",  # timezone-naive datetime.now()
]

[tool.ruff.lint.isort]
known-first-party = ["lycil"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.pytest.ini_options]
minversion = "9.0"
addopts = "--import-mode=importlib"
filterwarnings = [
    "ignore::UserWarning:Precision 16-mixed is not supported by the model summary*",
    "ignore::DeprecationWarning:This process * is multi-threaded, use of fork() may lead to deadlocks in the child.",
]
markers = [
    "runs_on: mark tests requiring specific device type, e.g. @pytest.mark.runs_on(['cuda'])",
    "slow: mark tests as slow (pytest -m 'not slow' or set RUN_SLOW=1 to run)",
    "distributed: mark tests requireing multi-device execution",
]
