[pytest]
markers = 
    runs_on: mark tests requiring specific device type, e.g. @pytest.mark.runs_on(['cuda'])
    slow: mark tests as slow (pytest -m "not slow" or set RUN_SLOW=1 to run)
    distributed: mark tests requireing multi-device execution