name: "\U0001F31F New learner addition"
description: Submit a proposal/request to implement a new learner
labels: [ "New learner" ]

body:
  - type: textarea
    id: description-request
    validations:
      required: true
    attributes:
      label: Learner description
      description: |
        Put any and all important information relative to the learner

  - type: checkboxes
    id: information-tasks
    attributes:
      label: Open source status
      description: |
          Please note that if the learner implementation isn't available, we are less likely to implement it in `LyCIL`.
      options:
        - label: "The learner implementation is available"

  - type: textarea
    id: additional-info
    attributes:
      label: Provide useful links for the implementation
      description: |
        Please provide information regarding the implementation, the weights, and the authors.
        Please mention the authors by @gh-username if you're aware of their usernames.